services:
  python-ai:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/docs" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    build:
      context: ./AI # Đường dẫn đến thư mục chứa Dockerfile.python và ai_service.py
      dockerfile: Dockerfile
    # Không cần 'ports' vì chỉ Java mới gọi nó (gọi nội bộ)
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Truyền API key vào
    networks:
      default:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt_broker/mosquitto/config:/mosquitto/config
      - ./mqtt_broker/mosquitto/data:/mosquitto/data
      - ./mqtt_broker/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: iot_db
    volumes:
      - ./mqtt_broker/mysql_data:/var/lib/mysql
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - default

  redis:
    image: redis:7.0
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./mqtt_broker/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: iot:latest
    container_name: smart_garden_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/iot_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - MQTT_BROKER_URL=tcp://mosquitto:1883
      - AI_SERVICE_URL=http://python-ai:8000/chat
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
        # (Các API Key nên được truyền vào đây)
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    depends_on:
      - mosquitto
      - mysql
      - redis
      - python-ai

volumes:
  mysql_data:
  redis_data:

networks:
  default:
    driver: bridge